services:
  ai_interview_backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI = mongodb+srv://adityawattamwar2004:<adityawattamwar2004>@cluster0.xl2i5.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - CORS_ORIGINS=http://localhost:5173,http://frontend:5173
      - CORS_SUPPORTS_CREDENTIALS=true
      - CORS_ALLOW_HEADERS=Content-Type,Authorization
      - CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - GROQ_KEY=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
    volumes:
      - ./backend/.env:/app/.env:ro
      - ./backend/uploads:/app/uploads
      - ./backend/flask_session:/app/flask_session
      - ./backend/logs:/app/logs
    restart: unless-stopped
    command: python -m flask run --host=0.0.0.0 --port=5000

  ai_interview_frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000/api
      - HOST=0.0.0.0
      - PORT=5173
      - VITE_FIREBASE_API_KEY=AIzaSyA60T4lnk197RT93ESNOawYaT_vGMZUeeo
      - VITE_FIREBASE_AUTH_DOMAIN=ai-interview-e8ca2.firebaseapp.com
      - VITE_FIREBASE_PROJECT_ID=ai-interview-e8ca2
      - VITE_FIREBASE_STORAGE_BUCKET=ai-interview-e8ca2.firebasestorage.app
      - VITE_FIREBASE_MESSAGING_SENDER_ID=335534385796
      - VITE_FIREBASE_APP_ID=1:335534385796:web:a018ca016245484792b0d1
    volumes:
      - ./frontend/.env:/app/.env:ro
    depends_on:
      - ai_interview_backend
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0 --port 5173
